SELECT 
	DAY,
	HOST,
	INDEXSERVER_ACTUAL_ROLE,
	BACKUP_SIZE_GB
FROM 
	(SELECT	
		BACKUP_ID,
		TO_CHAR(SYS_START_TIME,'YYYY/MM/DD') AS DAY,
		TO_CHAR(ADD_DAYS(SYS_START_TIME,1),'YYYY/MM/DD') AS DAY_PLUS_ONE,
		STATE_NAME,
		ENTRY_TYPE_NAME
	FROM M_BACKUP_CATALOG 
	WHERE 
		ENTRY_TYPE_NAME = 'complete data backup' AND 
		STATE_NAME = 'successful' /*Only successful data backup will be calculated*/
	) C
	JOIN 
	(SELECT 
		BACKUP_ID,
		MF.HOST,
		INDEXSERVER_ACTUAL_ROLE,
		ROUND(SUM(BACKUP_SIZE/1024/1024/1024),2) AS BACKUP_SIZE_GB
	FROM 
		M_BACKUP_CATALOG_FILES MF JOIN M_LANDSCAPE_HOST_CONFIGURATION HC
		ON MF.HOST = HC.HOST 	/*Add host role*/
	GROUP BY 
		MF.HOST,
		INDEXSERVER_ACTUAL_ROLE,
		BACKUP_ID
	) F
	ON C.BACKUP_ID = F.BACKUP_ID 
WHERE
	DAY_PLUS_ONE = TO_CHAR(current_date,'YYYY/MM/DD') 
ORDER BY DAY DESC,HOST
LIMIT 16

